import bs.ModLoader
import bs.SemverUtils
import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import org.apache.ivy.osgi.util.Version

import java.nio.file.Files
import java.nio.file.StandardCopyOption

import static bs.ModLoader.*

plugins {
    id 'java'
}

group = project.properties.mod_package
version = rootProject.properties.mod_version
ModLoader loader = ModLoader.fromProject(project)
archivesBaseName = "${rootProject.properties.mod_id}-$project.properties.minecraft-$loader.friendlyName"

def packageJar = tasks.create("packageJar", Copy.class) {
    into("${rootProject.layout.buildDirectory.get()}/libs/${E.p["mod_version"]}")
}


//// Copy built jar to root project's build/libs
//tasks.named("build") {
//    doLast {
//        def targetDir = layout.projectDirectory.dir("../../build/libs").asFile
//        layout.projectDirectory.dir("build/libs").asFile.listFiles()?.forEach { it.copyTo(targetDir.resolve(it.name), true) }
//    }
//}

project.ext["loom.platform"] = loader.friendlyName

repositories {
    mavenCentral()
    // for Mod Menu
    maven { url "https://maven.shedaniel.me/" }
    maven {
        url = "https://maven.terraformersmc.com/releases"
    }
    maven {
        url "https://maven.nucleoid.xyz/"
        name "Nucleoid"
    }
    // For NeoForge
    maven {
        url = "https://maven.neoforged.net/releases"
    }
    // For NeoForge PRs
    if (project.properties.neoforge_pr) {
        maven {
            url "https://prmaven.neoforged.net/NeoForge/pr$project.properties.neoforge_pr"
            content {
                includeModule("net.neoforged", "neoforge")
            }
        }
    }
    // For Patchment mappings
//    if (project.properties.parchment_version) {
//        maven {
//            name = 'ParchmentMC'
//            url = 'https://maven.parchmentmc.org'
//        }
//    }
    // For Forge
    maven {
        url = "https://maven.minecraftforge.net/"
    }
    //MidnightLib
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven { url = "https://jitpack.io" }

}
apply plugin: 'dev.architectury.loom'
stonecutter.const("fabric", loader == FABRIC)
stonecutter.const("forge", loader == FORGE)
stonecutter.const("neoforge", loader == NEOFORGE)
loom {

    runConfigs.all {
        ideConfigGenerated true // Run configurations are not created for subprojects by default
        runDir "../../run" // Use a shared run folder and just create separate worlds
    }

    // Env configuration
stonecutter {

        if (eval(minecraft, ">=1.20.6")) {
            System.out.println("Java 21")
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        } else if (eval(minecraft, ">=1.17")) {
            System.out.println("Java 17")
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        } else {
            System.out.println("Java 8")
            sourceCompatibility = JavaVersion.VERSION_1_8
            targetCompatibility = JavaVersion.VERSION_1_8
        }

}


    File file = project.buildDir.toPath().resolve("chiseledSrc/main/resources/${E.p.mod_id}.accesswidener").toFile()
    if (file.exists()) {
        accessWidenerPath = file
    } else {
        project.logger.warn("Access widener file not generated yet!")
    }
}
// Use vanilla mixin on Forge
if (loader == FORGE) {
    loom {
        forge {
            useCustomMixin = false

            mixinConfig "${E.p.mod_id}.mixins.json"
        }
    }
}

dependencies {

    minecraft "net.minecraft:minecraft:$project.properties.minecraft"
    mappings(loom.layered {
        mappings "net.fabricmc:yarn:${project.properties.yarn_mappings}:v2"
        if (stonecutter.eval(minecraft, ">=1.20.6") && loader == NEOFORGE) {
            mappings("dev.architectury:yarn-mappings-patch-neoforge:${minecraft}+build.4")
        }
    })

//
//    if (project.properties.parchment_version) {
//        mappings loom.layered {
//            officialMojangMappings()
//            parchment("org.parchmentmc.data:parchment-${project.properties.parchment_version}@zip")
//        }
//    } else {
//        mappings loom.officialMojangMappings()
//    }
    if (loader == FABRIC) {
        modImplementation "net.fabricmc:fabric-loader:$project.properties.fabricloader"
        modCompileOnly "com.terraformersmc:modmenu:$project.properties.modmenu", {
            // Don't transitively pull in Mod Menu's Fabric deps
            exclude module: "net.fabricmc"
            exclude module: "net.fabricmc.fabric-api"
        }
        modLocalRuntime "com.terraformersmc:modmenu:$project.properties.modmenu", {
            // Don't transitively pull in Mod Menu's Fabric deps
            exclude module: "net.fabricmc"
            exclude module: "net.fabricmc.fabric-api"
        }
//        if (stonecutter.eval(minecraft, "<=1.14.4")) {
//            modApi "me.shedaniel.cloth:config-2:1.8"
//        } else {
//            modApi "me.shedaniel.cloth:cloth-config-fabric:$project.properties.cloth_config_version"
//        }
        if (project.properties.fabric_api_modules == "*") {
            if (project.properties.include_fabric_api_modules == "true") {
                throw new RuntimeException("You can't include the entirety of Fabric API!")
            }
            modApi "net.fabricmc.fabric-api:fabric-api:$project.properties.fabric_api_version"
        } else {
            for (String module in project.properties.fabric_api_modules.split(",") as String[]) {
                var dep = fabricApi.module(module, "$project.properties.fabric_api_version")
                modApi dep
                if (project.properties.include_fabric_api_modules == "true") {
                    include(dep)
                }
            }
        }
    } else if (loader == FORGE) {
        implementation 'com.google.code.gson:gson:2.8.8'

        forge "net.minecraftforge:forge:$project.properties.forge"
//        if (stonecutter.eval(minecraft, "<=1.14.4")) {
//            modApi "me.shedaniel.cloth:config-2:1.8"
//        } else {
//            modApi "me.shedaniel.cloth:cloth-config-forge:$project.properties.cloth_config_version"
//        }
    } else if (loader == NEOFORGE) {
        neoForge "net.neoforged:neoforge:$project.properties.neoforge"
        //modApi "me.shedaniel.cloth:cloth-config-neoforge:$project.properties.cloth_config_version"
    }
    modImplementation "maven.modrinth:midnightlib:${project.midnightlib_version}"
    include "maven.modrinth:midnightlib:${project.midnightlib_version}"
}

//afterEvaluate {
//    def hasApplicableMixinExtras = project.getConfigurations().getByName("runtimeClasspath").getAllDependencies().stream().anyMatch(a -> {
//        return a.getName().startsWith("mixinextras") && a.getGroup().equals("io.github.llamalad7") && new Version(a.getVersion()) >= (new Version(project.properties.mixinextras.toString()))
//    })
//
//    if (!hasApplicableMixinExtras) {
//        dependencies {
//            implementation include("io.github.llamalad7:mixinextras-$loader.friendlyName:$project.properties.mixinextras")
//            if (loader == FORGE || loader == NEOFORGE) {
//                forgeRuntimeLibrary "io.github.llamalad7:mixinextras-$loader.friendlyName:$project.properties.mixinextras"
//            }
//        }
//    }
//}

jar {
    from(project.file("LICENSE")) {
        rename { "${it}_${archivesBaseName}"}
    }
}

processResources {
    def dep = project.properties.minecraft_dependency.toString()
    if (loader == FORGE || loader == NEOFORGE) {
        dep = SemverUtils.convertSemverPredicateToMavenPredicate(dep)
    }

    inputs.property "forgeid", loader == NEOFORGE ? "neoforge" : "forge"
    inputs.property "minecraft_dependency", dep
    inputs.property "mod_version", version
    inputs.property "mod_id", project.properties.mod_id
    inputs.property "mod_display_name", project.properties.mod_display_name
    inputs.property "mod_description", project.properties.mod_description
    inputs.property "homepage_url", project.properties.homepage_url
    inputs.property "sources_url", project.properties.sources_url
    inputs.property "issue_tracker_url", project.properties.issue_tracker_url
    inputs.property "license", project.properties.license
    inputs.property "fabricloader", project.properties.fabricloader
    inputs.property "contributors", project.properties.mod_contributors.toString()
    inputs.property "authors", project.properties.mod_authors.toString()
    inputs.property "fabric_api_modules", project.properties.fabric_api_modules

    filesMatching(["fabric.mod.json", "META-INF/mods.toml", "quilt.mod.json"]) {
        def map = [
                "forgeid": loader == NEOFORGE ? "neoforge" : "forge",
                "minecraft": dep,
                "mod_version": version,
                "mod_id": project.properties.mod_id,
                "mod_display_name": project.properties.mod_display_name,
                "mod_description": project.properties.mod_description,
                "homepage_url": project.properties.homepage_url,
                "sources_url": project.properties.sources_url,
                "issue_tracker_url": project.properties.issue_tracker_url,
                "license": project.properties.license,
                "fabricloader": project.properties.fabricloader,
                "contributors": project.properties.mod_contributors.toString().split(","),
                "authors": project.properties.mod_authors.toString().split(",")
        ]
        expand map
    }
    doLast {
        if (loader == NEOFORGE) {
            fileTree(dir: outputs.files.asPath, include: "META-INF/mods.toml").each { File file ->
                file.text += "\n\n[[mixins]]\nconfig = \"${project.properties.mod_id}.mixins.json\""
            }
            fileTree(dir: outputs.files.asPath, include: "META-INF/mods.toml").each { File file ->
                Files.copy(file.toPath(), java.nio.file.Path.of(outputs.files.asPath).resolve("META-INF/neoforge.mods.toml"), StandardCopyOption.REPLACE_EXISTING)
                file.delete()
            }
        }
        if (loader == FABRIC) {
            fileTree(dir: outputs.files.asPath, include: "fabric.mod.json").each { File file ->
                def parse = new JsonSlurper().parse(file)
                def fModulesString = project.properties.fabric_api_modules
                if (fModulesString == "*") {
                    parse.depends["fabric"] = ">=" + project.properties.fabric_api_version
                } else {
                    def fModules = fModulesString.split(",")
                    for (String s in fModules) {
                        // ^ means until the next major
                        parse.depends[s] = "^" + fabricApi.module(s, project.properties.fabric_api_version).getVersion()
                    }
                }
                file.text = JsonOutput.prettyPrint(JsonOutput.toJson(parse))
            }
        }
    }

    if (loader == FORGE || loader == NEOFORGE) {
        exclude 'fabric.mod.json'
    } else if (loader == FABRIC) {
        exclude 'META-INF/mods.toml', 'META-INF/accesstransformer.cfg', 'pack.mcmeta'
    }
}

remapJar {
    if (loader == FORGE || loader == NEOFORGE) {
        atAccessWideners.add("${project.properties.mod_id}.accesswidener")
    }
}

if (loader == FORGE) {
    configurations.all {
        resolutionStrategy {
            force 'net.sf.jopt-simple:jopt-simple:5.0.4'
        }
    }
}

if (loader == FABRIC) {
    configurations.all {
        resolutionStrategy {
            force("net.fabricmc:fabric-loader:$fabricloader")
        }
    }
}

afterEvaluate {
    packageJar.dependsOn(remapJar)
    packageJar.from(remapJar.archiveFile)
    build.finalizedBy(packageJar)
}